MVCDemoSolution/MVCDemo/Models/BaseProductViewModel.cs
namespace MVCDemo.Models
{
    public class BaseProductViewModel
    {
        public IReadOnlyList<ProductDetailsViewModel> Products { get; set; }
        public int Count { get; set; }
        public DateTime LatestOrderDate { get; set; }
    }
}

MVCDemoSolution/MVCDemo/Models/EmployeeViewModel.cs
namespace MVCDemo.Models
{
    public class EmployeeViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public DateTime CreatedDate { get; set; }
        public int YearsOfExperience { get; set; }

        public bool IsPermanentEmployee
        {
            get
            {
                return YearsOfExperience >= 5;
            }
        }

        public string RowCssColor
        {
            get
            {
                return IsPermanentEmployee ? "blue" : "yellow";
            }
        }
    }
}

MVCDemoSolution/MVCDemo/Models/ErrorViewModel.cs
namespace MVCDemo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCDemoSolution/MVCDemo/Models/ProductDetailsViewModel.cs
namespace MVCDemo.Models
{
    public class ProductDetailsViewModel
    {
        public Guid Id { get; set; }
        public string ProductName { get; set; }
        public Category ProductCategory { get; set; }
        public OrderStatus Status { get; set; }
        public DateTime? OrderedDate { get; set; }
    }

    public enum Category
    {
        CPUs,
        GraphicCards,
        Keyboards
    }

    public enum OrderStatus
    {
        Ordered,
        InTransit,
        Delivered
    }
}

MVCDemoSolution/MVCDemo/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCDemo.Models;

namespace MVCDemo.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details()
        {
            return View();
        }

        public IActionResult EmployeeDetails()
        {
            var employees = new List<EmployeeViewModel>
            {
                new EmployeeViewModel
                {
                    Id=101,
                    Name="Arshad",
                    City="Hyd",
                    CreatedDate=DateTime.Now,
                    YearsOfExperience=6
                },
                new EmployeeViewModel
                {
                    Id=102,
                    Name="Abhishek",
                    City="Hyd",
                    CreatedDate=DateTime.Now.AddMinutes(10),
                    YearsOfExperience=4
                },
                new EmployeeViewModel
                {
                    Id=103,
                    Name="Sanjay",
                    City="Hyd",
                    CreatedDate=DateTime.Now.AddMinutes(20),
                    YearsOfExperience=8
                },
            };

            return View(employees);
        }
    }
}

MVCDemoSolution/MVCDemo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCDemo.Models;
using System.Diagnostics;

namespace MVCDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Index1()
        {
            return Content("Index1");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCDemoSolution/MVCDemo/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using MVCDemo.Data;
using MVCDemo.Models;

namespace MVCDemo.Controllers
{
    public class ProductsController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Country"] = "India";
            ViewData["PrimeNumber"] = 3;

            var model = new EmployeeViewModel
            {
                Id = 23,
                Name = "John"
            };

            ViewData["EmpModel"] = model.Name;

            ViewBag.FirstName = "John";
            ViewBag.LastName = "Doe";
            ViewBag.CreatedDate = DateTime.Now;
            ViewBag.IsAContractualEmployee = true;

            return View();
        }

        public IActionResult ProductDetails()
        {
            var model = ProductRepository.GetProducts();
            return View(model);
        }

        public IActionResult ProductReport()
        {
            var products = ProductRepository.GetProducts();
            var model = new BaseProductViewModel
            {
                Products = products,
                Count = products.Count(),
                LatestOrderDate = products.Max(x => x.OrderedDate).Value
            };
            return View(model);
        }
    }
}

MVCDemoSolution/MVCDemo/Views/Employee/Details.cshtml
<h1>Hello from Employee controller, Details View</h1>

<div class="center">
    <table border="1" width="500px">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>City</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>John</td>
                <td>Chicago</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Mary</td>
                <td>New York</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Dave</td>
                <td>LA</td>
            </tr>
        </tbody>
    </table>

    <input type="text" value="Anurag"/>
    <button onclick="alert('Hey!!!')">Click Me</button>
</div>

MVCDemoSolution/MVCDemo/Views/Employee/EmployeeDetails.cshtml
@model List<EmployeeViewModel>
<h1>Employee Details</h1>

<div class="center">
    <table border="1" width="500px" style="background-color:chocolate">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>City</th>
                <th>Created Date</th>
                <th>Experience in years</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr style="background-color:@item.RowCssColor">
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.City</td>
                    <td>@item.CreatedDate</td>
                    <td>@item.YearsOfExperience</td>
                </tr>
            }
        </tbody>
    </table>
</div>

MVCDemoSolution/MVCDemo/Views/Employee/Index.cshtml
<h1>Hello from Employee controller, Index View</h1>

MVCDemoSolution/MVCDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1>Hello from Index View</h1>
</div>

MVCDemoSolution/MVCDemo/Views/Products/Index.cshtml
<h1>Products Controller - Index View</h1>

<p>@ViewData["Country"]</p>
<p>@ViewData["PrimeNumber"]</p>
<p>@ViewData["EmpModel"]</p>


<h1>ViewBag Examples</h1>
@{
    var fullName = $"{@ViewBag.FirstName} {@ViewBag.LastName}";
    var employeeStatus = @ViewBag.IsAContractualEmployee == true ? "contractual employee" : "permanent employee";
}

<h3>@fullName has been an employee since @ViewBag.CreatedDate</h3>
<h4>He is a @employeeStatus</h4>

MVCDemoSolution/MVCDemo/Views/Products/ProductDetails.cshtml
@model IEnumerable<ProductDetailsViewModel>

<div class="center">
    <table border="1" width="500px" style="background-color:chocolate">
        <thead>
            <tr>
                <th>Id</th>
                <th>Product Name</th>
                <th>Product Category</th>
                <th>Order Status</th>
                <th>Ordered Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.ProductName</td>
                    <td>@item.ProductCategory</td>
                    <td>@item.Status</td>
                    <td>@item.OrderedDate.Value.ToShortDateString()</td>
                </tr>
            }
        </tbody>
    </table>
</div>

MVCDemoSolution/MVCDemo/Views/Products/ProductReport.cshtml
@model BaseProductViewModel

<h2>Product Report</h2>
<p>Count - @Model.Count</p>
<p>Latest Order Date - @Model.LatestOrderDate.ToLongDateString()</p>

<h2>Products Info</h2>

<div class="center">
    <table border="1" width="100%" style="background-color:chocolate">
        <thead>
            <tr>
                <th>Id</th>
                <th>Product Name</th>
                <th>Product Category</th>
                <th>Order Status</th>
                <th>Ordered Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Products)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.ProductName</td>
                    <td>@item.ProductCategory</td>
                    <td>@item.Status</td>
                    <td>@item.OrderedDate.Value.ToShortDateString()</td>
                </tr>
            }
        </tbody>
    </table>
</div>

MVCDemoSolution/MVCDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Details">Employee Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmployeeDetails">Real Employee Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="ProductDetails">Product Details</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="ProductReport">Product Report</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>